# Generated by Django 4.2.20 on 2025-04-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fillInBlanks_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_1', models.CharField(max_length=60)),
                ('adjective_1', models.CharField(max_length=60)),
                ('US_state', models.CharField(max_length=60)),
                ('number_1', models.CharField(max_length=60)),
                ('past_tense_verb_1', models.CharField(max_length=60)),
                ('social_media', models.CharField(max_length=60)),
                ('number_2', models.CharField(max_length=60)),
                ('past_tense_verb_2', models.CharField(max_length=60)),
                ('political_organization_1', models.CharField(max_length=60)),
                ('adjective_2', models.CharField(max_length=60)),
                ('group_of_people', models.CharField(max_length=60)),
                ('political_organization_2', models.CharField(max_length=60)),
                ('verb_ing', models.CharField(max_length=60)),
                ('past_tense_emotion', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('age', models.CharField(max_length=60)),
                ('political_issue', models.CharField(max_length=60)),
                ('Adjective_3', models.CharField(max_length=60)),
                ('Adjective_4', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'fillInBlanks_1',
            },
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
