# Generated by Django 4.2.20 on 2025-04-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_fillinblanks_1_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks_1',
            name='emotion_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
