# Generated by Django 4.2.20 on 2025-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_fillinblanks_1_emotion_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='fillInBlanks_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_1', models.CharField(max_length=60)),
                ('country_2', models.CharField(max_length=60)),
                ('political_organization', models.CharField(max_length=60)),
                ('social_media', models.CharField(max_length=60)),
                ('product', models.CharField(max_length=60)),
                ('government_role', models.CharField(max_length=60)),
                ('endearment', models.CharField(max_length=60)),
                ('noun', models.CharField(max_length=60)),
                ('plural_noun', models.CharField(max_length=60)),
                ('weapon', models.CharField(max_length=60)),
                ('name_1', models.CharField(max_length=60)),
                ('name_2', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'fillInBlanks_2',
            },
        ),
    ]
