# Generated by Django 4.2.20 on 2025-08-15 01:52

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_fillinblanks_1_storytname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks_1',
            name='storytname',
            field=models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True),
        ),
    ]
