# Generated by Django 4.2.20 on 2025-08-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_fillinblanks_1_storytname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillinblanks_1',
            old_name='storytname',
            new_name='idname',
        ),
    ]
