# Generated by Django 4.2.20 on 2025-08-22 15:51

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_storytname_fillinblanks_1_idname'),
    ]

    operations = [
        migrations.CreateModel(
            name='fillInBlanks_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('natural_disaster', models.CharField(max_length=60)),
                ('feeling', models.CharField(max_length=60)),
                ('movement_1', models.CharField(max_length=60)),
                ('movement_2', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=60)),
                ('farm_animal', models.CharField(max_length=60)),
                ('chain', models.CharField(max_length=60)),
                ('government_agency', models.CharField(max_length=60)),
                ('technology', models.CharField(max_length=60)),
                ('non_profit_agency', models.CharField(max_length=60)),
                ('adjective', models.CharField(max_length=60)),
                ('industry', models.CharField(max_length=60)),
                ('political_organization', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='fillInBlanks_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('sport', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('feeling', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=60)),
                ('event', models.CharField(max_length=60)),
                ('medical_provider', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=60)),
                ('media_company', models.CharField(max_length=60)),
                ('disease_1', models.CharField(max_length=60)),
                ('disease_2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='fillInBlanks_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('sporting_event', models.CharField(max_length=60)),
                ('government_role', models.CharField(max_length=60)),
                ('monarchal_country', models.CharField(max_length=60)),
                ('US_state', models.CharField(max_length=60)),
                ('name_1', models.CharField(max_length=60)),
                ('name_2', models.CharField(max_length=60)),
                ('vegetable', models.CharField(max_length=60)),
                ('social_media_1', models.CharField(max_length=60)),
                ('social_media_2', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='fillinblanks_2',
            name='group_of_people',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fillinblanks_2',
            name='idname',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
