# Generated by Django 4.2.20 on 2025-08-22 15:53

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_fillinblanks_3_fillinblanks_4_fillinblanks_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks_2',
            name='idname',
            field=models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True),
        ),
    ]
