# Generated by Django 4.2.20 on 2025-08-31 00:26

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_fillinblanks_2_idname'),
    ]

    operations = [
        migrations.CreateModel(
            name='fillInBlanks_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('emotion', models.CharField(max_length=60)),
                ('US_state', models.CharField(max_length=60)),
                ('Fraternity', models.CharField(max_length=60)),
                ('non_profit_agency', models.CharField(max_length=60)),
                ('number_1', models.CharField(max_length=60)),
                ('number_2', models.CharField(max_length=60)),
                ('name_1', models.CharField(max_length=60)),
                ('number_3', models.CharField(max_length=60)),
                ('name_2', models.CharField(max_length=60)),
                ('college_major', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='fillInBlanks_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('emotion', models.CharField(max_length=60)),
                ('soccer_league', models.CharField(max_length=60)),
                ('stadium', models.CharField(max_length=60)),
                ('team_1', models.CharField(max_length=60)),
                ('team_2', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='fillInBlanks_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default=posts.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('emotion', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('US_State_Capital', models.CharField(max_length=60)),
                ('past_tense_emotion', models.CharField(max_length=60)),
                ('social_media', models.CharField(max_length=60)),
                ('school_class', models.CharField(max_length=60)),
                ('school_mascot', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('lawn_game', models.CharField(max_length=60)),
            ],
        ),
    ]
